Resources:
  ASGInstanceSecurityGroup0525485D:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ApigwVpcNlbStack/ASG/InstanceSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        []
      Tags:
        - Key: Name
          Value: ApigwVpcNlbStack/ASG
      VpcId:
        Fn::ImportValue: Vpc:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/ASG/InstanceSecurityGroup/Resource
  ASGInstanceRoleE263A41B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/ASG/InstanceRole/Resource
  ASGInstanceProfile0A2834D7:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: ASGInstanceRoleE263A41B
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/ASG/InstanceProfile
  ASGLaunchConfigC00AF12B:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0080e4c5bc078760e
      InstanceType: t2.micro
      IamInstanceProfile:
        Ref: ASGInstanceProfile0A2834D7
      SecurityGroups:
        - Fn::GetAtt:
            - ASGInstanceSecurityGroup0525485D
            - GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
    DependsOn:
      - ASGInstanceRoleE263A41B
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/ASG/LaunchConfig
  ASG46ED3070:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
      LaunchConfigurationName:
        Ref: ASGLaunchConfigC00AF12B
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: ApigwVpcNlbStack/ASG
      TargetGroupARNs:
        - Ref: LBapi1listenerapi1targetGroup89457BBD
      VPCZoneIdentifier:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 1
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 2
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 3
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 4
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 5
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/ASG/ASG
  apigw188747F19:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: api-1
      RepositoryDescription: API -1 written in Node.js
      Triggers:
        []
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/apigw-1/Resource
  apigw2293C504B:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: api-2
      RepositoryDescription: API -2 written in Node.js
      Triggers:
        []
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/apigw-2/Resource
  apigw3103B831E:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: api-3
      RepositoryDescription: API -3 written in Node.js
      Triggers:
        []
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/apigw-3/Resource
  apiC8550315:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: api
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/Resource
  apiDeployment149F1294b280c4882b2264aeb67f4e94ebe60ee7:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: apiC8550315
      Description: Automatically created by the RestApi construct
    DependsOn:
      - apiANYB3DF8C3C
      - apiapi123B2CF66
      - apiapi1ANYD95F265D
      - apiapi203BCBB35
      - apiapi2ANY7C669D1C
      - apiapi362339D9A
      - apiapi3ANYFCA07956
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/Deployment/Resource
  apiDeploymentStageprod896C8101:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: apiC8550315
      DeploymentId:
        Ref: apiDeployment149F1294b280c4882b2264aeb67f4e94ebe60ee7
      StageName: prod
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/DeploymentStage.prod/Resource
  apiCloudWatchRoleAC81D93E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/CloudWatchRole/Resource
  apiAccount57E28B43:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - apiCloudWatchRoleAC81D93E
          - Arn
    DependsOn:
      - apiC8550315
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/Account
  apiANYB3DF8C3C:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        Type: MOCK
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/ANY/Resource
  apiapi123B2CF66:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      PathPart: api1
      RestApiId:
        Ref: apiC8550315
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/api1/Resource
  apiapi1ANYD95F265D:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: apiapi123B2CF66
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        Type: MOCK
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/api1/ANY/Resource
  apiapi203BCBB35:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      PathPart: api2
      RestApiId:
        Ref: apiC8550315
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/api2/Resource
  apiapi2ANY7C669D1C:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: apiapi203BCBB35
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        Type: MOCK
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/api2/ANY/Resource
  apiapi362339D9A:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      PathPart: api3
      RestApiId:
        Ref: apiC8550315
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/api3/Resource
  apiapi3ANYFCA07956:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: apiapi362339D9A
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        Type: MOCK
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/api/api3/ANY/Resource
  LB8A12904C:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        []
      Scheme: internal
      Subnets:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 1
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 2
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 3
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 4
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
        - Fn::Select:
            - 5
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
      Type: network
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/LB/Resource
  LBapi1listenerAAC7334B:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi1listenerapi1targetGroup89457BBD
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 2000
      Protocol: TCP
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/LB/api1_listener/Resource
  LBapi1listenerapi1targetGroup89457BBD:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 2000
      Protocol: TCP
      VpcId:
        Fn::ImportValue: Vpc:TheVPCVpcIdD346CDBA
      TargetGroupAttributes:
        []
      Targets:
        []
      TargetType: instance
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/LB/api1_listener/api1_targetGroup/Resource
  LBapi2listener9434057D:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi2listenerapi2targetGroupF044D51E
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 3000
      Protocol: TCP
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/LB/api2_listener/Resource
  LBapi2listenerapi2targetGroupF044D51E:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: TCP
      VpcId:
        Fn::ImportValue: Vpc:TheVPCVpcIdD346CDBA
      TargetGroupAttributes:
        []
      Targets:
        []
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/LB/api2_listener/api2_targetGroup/Resource
  LBapi3listenerC7F2EA36:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi3listenerapi3targetGroupAF4A1D8D
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 4000
      Protocol: TCP
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/LB/api3_listener/Resource
  LBapi3listenerapi3targetGroupAF4A1D8D:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 4000
      Protocol: TCP
      VpcId:
        Fn::ImportValue: Vpc:TheVPCVpcIdD346CDBA
      TargetGroupAttributes:
        []
      Targets:
        []
    Metadata:
      aws:cdk:path: ApigwVpcNlbStack/LB/api3_listener/api3_targetGroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: "@aws-cdk/aws-apigateway=0.20.0,@aws-cdk/aws-autoscaling=0.20.0,@aws-cd\
        k/aws-autoscaling-common=0.20.0,@aws-cdk/aws-cloudwatch=0.20.0,@aws-cdk\
        /aws-codecommit=0.20.0,@aws-cdk/aws-codedeploy-api=0.20.0,@aws-cdk/aws-\
        codepipeline-api=0.20.0,@aws-cdk/aws-ec2=0.20.0,@aws-cdk/aws-elasticloa\
        dbalancingv2=0.20.0,@aws-cdk/aws-events=0.20.0,@aws-cdk/aws-iam=0.20.0,\
        @aws-cdk/cdk=0.20.0,@aws-cdk/cx-api=0.20.0,jsii-runtime=node.js/v11.2.0"
Outputs:
  apiEndpoint9349E63C:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: apiC8550315
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - Ref: apiDeploymentStageprod896C8101
          - /
    Export:
      Name: ApigwVpcNlbStack:apiEndpoint9349E63C
